/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ArticleStatus } from '../models/article-status';
export interface ArticleDto {
  content?: (string | null);
  id?: (number | string);
  status?: ArticleStatus;
  title?: (string | null);
}
