/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ColourDto } from '../models/colour-dto';
import { LookupDto } from '../models/lookup-dto';
import { TodoListDto } from '../models/todo-list-dto';
export interface TodosVm {
  colours?: Array<ColourDto>;
  lists?: Array<TodoListDto>;
  priorityLevels?: Array<LookupDto>;
}
