/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TodoItemDto } from '../models/todo-item-dto';
export interface TodoListDto {
  colour?: (string | null);
  id?: (number | string);
  items?: Array<TodoItemDto>;
  title?: (string | null);
}
