/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TodoItemDto {
  done?: boolean;
  id?: (number | string);
  listId?: (number | string);
  note?: (string | null);
  priority?: (number | string);
  title?: (string | null);
}
