/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PriorityLevel } from '../models/priority-level';
export interface UpdateTodoItemDetailCommand {
  id?: (number | string);
  listId?: (number | string);
  note?: (string | null);
  priority?: PriorityLevel;
}
