/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ArticleStatus } from '../models/article-status';
export interface UpdateArticleItemDetailCommand {
  content?: (string | null);
  id?: (number | string);
  status?: (null | ArticleStatus);
  title?: (string | null);
}
