/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WeatherForecast {
  date?: string;
  summary?: string;
  temperatureC?: (number | string);
  temperatureF?: (number | string);
}
