/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AccessTokenResponse } from '../../models/access-token-response';
import { LoginRequest } from '../../models/login-request';

export interface ApiUsersLoginPost$Params {
  useCookies?: boolean;
  useSessionCookies?: boolean;
      body: LoginRequest
}

export function apiUsersLoginPost(http: HttpClient, rootUrl: string, params: ApiUsersLoginPost$Params, context?: HttpContext): Observable<StrictHttpResponse<AccessTokenResponse>> {
  const rb = new RequestBuilder(rootUrl, apiUsersLoginPost.PATH, 'post');
  if (params) {
    rb.query('useCookies', params.useCookies, {});
    rb.query('useSessionCookies', params.useSessionCookies, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AccessTokenResponse>;
    })
  );
}

apiUsersLoginPost.PATH = '/api/Users/login';
