/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateTodoListCommand } from '../../models/create-todo-list-command';

export interface CreateTodoList$Params {
      body: CreateTodoListCommand
}

export function createTodoList(http: HttpClient, rootUrl: string, params: CreateTodoList$Params, context?: HttpContext): Observable<StrictHttpResponse<(number | string)>> {
  const rb = new RequestBuilder(rootUrl, createTodoList.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<(number | string)>;
    })
  );
}

createTodoList.PATH = '/api/TodoLists';
