/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TodosVm } from '../../models/todos-vm';

export interface GetTodoLists$Params {
}

export function getTodoLists(http: HttpClient, rootUrl: string, params?: GetTodoLists$Params, context?: HttpContext): Observable<StrictHttpResponse<TodosVm>> {
  const rb = new RequestBuilder(rootUrl, getTodoLists.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TodosVm>;
    })
  );
}

getTodoLists.PATH = '/api/TodoLists';
